# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
